<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>registration_buyCardChkbox</name>
   <tag></tag>
   <elementGuidId>44149dae-96ad-49d6-83d0-a65cb9148257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combinedRegistrationForm__wtcth_combinedRegistrationForm_step4__0__purchaseOption__false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
