<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkout_qrCodeBtn</name>
   <tag></tag>
   <elementGuidId>80e187e6-6e64-4e6a-aa68-fdcd463fea04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='KBankWhiteLabelQr']/..</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radiobtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/main[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container-left&quot;]/section[@class=&quot;container-checkout-paymentMethod&quot;]/div[@class=&quot;detail&quot;]/div[@class=&quot;checkout-paymentMethod-details&quot;]/div[@class=&quot;paymentMethod-details&quot;]/div[@class=&quot;payment-method payment-way-check tabPaymentVisa&quot;]/div[@class=&quot;form-group payment-way-check-line&quot;]/label[@class=&quot;checkbox-label&quot;]/span[@class=&quot;radiobtn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/main/div/div/section[4]/div[2]/div[3]/div/div/div[3]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span</value>
   </webElementXpaths>
</WebElementEntity>
