<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgetPw_emailField</name>
   <tag></tag>
   <elementGuidId>71bda6a5-cde7-41e0-9924-d56691c65513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forgottenPasswordByEmailForm__wtcth_forgottenPasswordByEmailForm_step1__2__email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
