<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>brandLandingPage_Product1_QuickAddToBasketBtn</name>
   <tag></tag>
   <elementGuidId>2ca0b4bf-1078-42a7-bc5b-0519f7bc6ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='btn btn-primary btn-add-to-cart iconOnly ng-star-inserted'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-shopping-bag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/main[@class=&quot;PLP&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;PLP_content&quot;]/div[@class=&quot;contentRight&quot;]/div[@class=&quot;ProductSales&quot;]/div[@class=&quot;bottomProductSales&quot;]/div[@class=&quot;productItemContainer&quot;]/div[@class=&quot;productNameInfo&quot;]/div[@class=&quot;btn-add-to-bag buy in-stock&quot;]/i[@class=&quot;icon-shopping-bag&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/main/div/div[2]/div[2]/div[5]/div/div[2]/div[3]/div[5]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[5]/i</value>
   </webElementXpaths>
</WebElementEntity>
