<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>brandLandingPage_Banner</name>
   <tag></tag>
   <elementGuidId>5143df18-77c0-489a-8a1c-957dd393b61b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gtmBanner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-slot[contains(@class,'Banner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-desktop</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-tablet</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-mobile</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gtmBanner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-banner-creative</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-banner-impression-done</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-list</name>
      <type>Main</type>
      <value>category-name-banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>/medias/Long-Promotion-Banner-1005x140.jpg?context=bWFzdGVyfHJvb3R8MTE2ODh8aW1hZ2UvanBlZ3xoNDcvaDlmLzg4MjMxOTg5NDEyMTQuanBnfDgxZTU2ZDUzMmNjMmEyZGM1NjNlMDhlYjhkMDkyNTU4NjkxZGNmMDBmNDY0YzdhNzk3ZWZiOWJlYWVjMTk3ZTI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/main[@class=&quot;PLP&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;PLP_content&quot;]/div[@class=&quot;contentRight&quot;]/div[@class=&quot;PLP_banner&quot;]/a[@class=&quot;ClickBannerEvent_Class responsiveImageCom&quot;]/img[@class=&quot;gtmBanner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/main/div/div[2]/div[2]/div[2]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
