<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>whiteLabelPayment_qrCodeID</name>
   <tag></tag>
   <elementGuidId>0d7dcebf-0521-46b0-b3b6-5bfc69ea6fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-show-qr-id > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'qr_test_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qr_test_203266b45f7a06193432aa2b8a4f370feb480</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-kpayment[1]/div[@class=&quot;warp-content&quot;]/div[@class=&quot;card-view&quot;]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;tab-content&quot;]/div[1]/div[1]/app-qr-payment[1]/div[@class=&quot;text-inquiry-qr&quot;]/div[@class=&quot;text-show-qr-id&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This page will be automatically updated with a payment result within 30 seconds.'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='qr_test_203266b45f7a06193432aa2b8a4f370feb480']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
