<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home_watsonsLogo</name>
   <tag></tag>
   <elementGuidId>b6bed7f0-da7e-4004-b725-35cf0b1b1649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lazyImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-slot[@class='SiteLogo has-components ng-star-inserted']/*/*/*/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyImg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/watsons-logo-UAT.png?context=bWFzdGVyfHJvb3R8MTM0NTV8aW1hZ2UvcG5nfGg5NC9oNGEvODkzOTk0NjM0NDQ3OC5wbmd8ZGQ0OGE5NmQ4ZmYyOTU2YzIyMjQxZjIxOGYxOWM3OWJkMmQzNTcwMzZiNWM1YzBmODIxMDk3MGExMjY0Y2FkOA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>watsons-logo-UAT.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/medias/watsons-logo-UAT.png?context=bWFzdGVyfHJvb3R8MTM0NTV8aW1hZ2UvcG5nfGg5NC9oNGEvODkzOTk0NjM0NDQ3OC5wbmd8ZGQ0OGE5NmQ4ZmYyOTU2YzIyMjQxZjIxOGYxOWM3OWJkMmQzNTcwMzZiNWM1YzBmODIxMDk3MGExMjY0Y2FkOA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>watsons-logo-UAT.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>/medias/watsons-logo-UAT.png?context=bWFzdGVyfHJvb3R8MTM0NTV8aW1hZ2UvcG5nfGg5NC9oNGEvODkzOTk0NjM0NDQ3OC5wbmd8ZGQ0OGE5NmQ4ZmYyOTU2YzIyMjQxZjIxOGYxOWM3OWJkMmQzNTcwMzZiNWM1YzBmODIxMDk3MGExMjY0Y2FkOA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalWrapper&quot;)/header[@class=&quot;bootstrap&quot;]/div[@class=&quot;headerLogoBar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;topLogo pull-left&quot;]/a[1]/div[@class=&quot;clearfix banner center&quot;]/img[@class=&quot;lazyImg&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='globalWrapper']/header/div[3]/div/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='watsons-logo-UAT.png']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
   </webElementXpaths>
</WebElementEntity>
