<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_updateMobileOTP</name>
   <tag></tag>
   <elementGuidId>1740b79d-8f99-431c-99bc-0e035f99c1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//e2-otp-sms/*/input[@type='text']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
