<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_CategoryFilter</name>
   <tag></tag>
   <elementGuidId>0ec0029e-165f-4407-ae4b-39eae1c1563b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.PLP-Filter.open-level3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-slot[contains(@class,'ProductRefinement')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PLP-Filter open-level3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	
		










	
	
	
	
	
	
	
												
													Category
													
												
												
													
													
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																SKII(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																保健(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																保濕面膜(60)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																保濕面膜(29)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																保養(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																凍膜(13)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																凝露 / 凝凍(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																化妝水 / 噴霧(3)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																口腔保健(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																女性保健(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																專櫃(15)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																專櫃(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																強健髮根 / 頭皮護理(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																日用(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																日韓品牌(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																歐美品牌(13)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																洗髮 / 潤髮(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																清潔(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																牙膏(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																特惠組 / 體驗組(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																珍珠粉/燕窩(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																眼膜(3)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																粉餅/蜜粉(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																精華液 / 精華(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																緊緻面膜(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																美體美髮(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																臉部保養(103)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																臉部保養(61)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																臉部保養(10)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																臉部去角質(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																臉部彩妝(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																自有品牌(10)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																醫美(13)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																醫美保養(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																開架彩妝(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																面膜(82)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																面膜(60)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																面膜(32)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																面膜(10)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																面膜 / 凍膜(11)
															
														
													
															清除設定
															
																顯示全部
																隱藏
															
														
													
											
										
	
												
													品牌
													
												
												
													
													
															
															
															
														
													
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																1028(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																50惠(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																ALBION(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																ALBION艾倫比亞(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Avene 雅漾(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BEAUTYBUFFET(9)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BEAUTYMATE美肌之誌(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BIOESSENCE(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BIORE(3)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BONANZA(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																BONANZA 寶藝(3)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Bio-essence 碧歐斯(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Bio-essence碧歐斯(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																DAIFIEEL(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																DR.WU(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Dr's Formula(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Dr. Morita 森田藥粧(9)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Dr.Satin(6)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																ELE(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																ESTEE LAUDER(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																FORENCOS(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																HADALABO肌研(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																HIKARU(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																HUATUO 華陀扶元堂(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																INSTITUTKARITEPARIS(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Institut Karite Paris巴黎乳油木(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																JINGCHENG(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Jericho(1)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																KOSE(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																KOSE 高絲(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																MYSCHEMING我的心機(6)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																NARUKO(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																NARUKO 牛爾親研(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Neutrogena 露得清(6)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																ORIGINS 品木宣言(10)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																POKEMON(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Pure Beauty(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																SHISEIDO 資生堂(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																SKINBIOTEC(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																SWISSVITA(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																VALENTINO(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																Watsons 屈臣氏(5)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																divinia 蒂芬妮亞(10)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																俏佳人(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																天天美麗(58)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																寵愛之名(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																廣源良(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																有機沛特斯 Petal Fresh(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																美舒律(2)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																肌研(2)
															
														
													
															清除設定
															
																顯示全部
																隱藏
															
														
													
											
										
	
										
											配送方式
											
										
										
											
												
													
															 
															 
															 
															 
															 
															
															
															
															 
															
														
													宅配到府
												
												
												
															
																	
																	 
																	 
																	 
																	 
																	
																	
																	
																	
																	
																
															屈臣氏門市取貨
														
														
																
																		
																		 
																		 
																		 
																		 
																		
																		
																		
																		
																		
																	
																超商取貨
															
														
										
									
								
	
										
											海外運送
											
										
										
											
												
															
																	 
																	 
																	 
																	 
																	 
																	
																	
																	
																	 
																	
																
															提供海外運送服務
														
													
										
									
								
	










	價格 
	 
					
			
				
					$
				
									
			
			
			
				
			
			
				
			
			
			至
					
						
						
		
		Please enter &quot;To&quot; value more
		
			重設
			查詢
		
	


	
	 
	 
	 
	 
	 
	 
	
	
	 


	
												
													促銷
													
												
												
													
													
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																刷中信卡滿988享88折(4)
															
														
																
																	
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																		
																	
																
																滿1500送100(6)
															
														
													
											
										
	
										
													
														
																 
																 
																 
																 
																 
																
																
																
																 
																
															
														有庫存
													
												
											
								
 
	 
	 
	 
	 
	
	
	
	
	
	
	 
	

	
	
	 
	 
	 
	 
	
	
	
	
	
	
	
	
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/main[@class=&quot;PLP search-result&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;PLP_content&quot;]/div[@class=&quot;contentLeft&quot;]/div[@class=&quot;PLP-Filter open-level3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/main/div/div[2]/div/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='面膜'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
