<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>basket_deliveryMethodDropdownBtn</name>
   <tag></tag>
   <elementGuidId>76ef30a8-96d3-4a03-b438-e4a2f46bec5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//e2-shopbag-delivery-method/div[@ngbdropdown]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
