<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>categoryLanding_Banner</name>
   <tag></tag>
   <elementGuidId>e3f8d2d1-a825-4def-b2c8-b6a82186f1c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.gtmBanner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-slot[contains(@class,'BannerCarousel')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-desktop</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-tablet</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src-mobile</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gtmBanner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>本檔必買_EC_1200x165OK.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>本檔必買_EC_1200x165OK.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-banner-name</name>
      <type>Main</type>
      <value>本檔必買_EC_1200x165OK.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-banner-creative</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-banner-impression-done</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-list</name>
      <type>Main</type>
      <value>category-name-banner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>/medias/-EC-1200x165OK.jpg?context=bWFzdGVyfHJvb3R8MTI2NjEyfGltYWdlL2pwZWd8aGE4L2g0NC84ODkzMjUxMzIxODg2LmpwZ3w4ZjUzMzIyNDYyNDk3ODE4MTlmZWQ1NGVhYzIzYjAyMDAxNThhM2ZiMzY3NWM4N2EzMjZlNDA1ODY4NzNiNmMw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/main[@class=&quot;Category_Landing_Page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;productContentLeftRightBox&quot;]/div[@class=&quot;productContentRightBox&quot;]/div[@class=&quot;category_name_banner&quot;]/a[@class=&quot;ClickBannerEvent_Class responsiveImageCom&quot;]/img[@class=&quot;gtmBanner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/main/div/div[2]/div[2]/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='本檔必買_EC_1200x165OK.jpg']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
