<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>basket_productInfoSubtotal</name>
   <tag></tag>
   <elementGuidId>9b8f2fc1-a8f8-405b-a5c5-080d5a35622f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.td.myBasketTableProductSubtotal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'product-total')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td myBasketTableProductSubtotal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		            		$1,497
		                 	</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;globalWrapperMyBag&quot;]/main[@class=&quot;shop_bag&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;shopBagContentbLeftBottomBox applyDesktopMinHeight&quot;]/div[@class=&quot;myBasketContent part-watson-delivery&quot;]/div[@class=&quot;myBasketTable&quot;]/div[@class=&quot;myBasketTableProduct&quot;]/div[@class=&quot;myBasketTableProductBox clearfix&quot;]/div[@class=&quot;td myBasketTableProductSubtotal&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/main/div/div[3]/div/div[3]/div[2]/div[2]/div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='更新'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$499'])[1]/following::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[6]</value>
   </webElementXpaths>
</WebElementEntity>
